services:
  backend:
    &backend
    env_file: .env
    build: ./backend
    restart: always
    volumes:
      - ./backend:/backend
      - ./backend/scripts/entrypoint-backend.sh:/entrypoint-backend.sh
      - ./backend/certs:/backend/certs:ro
    working_dir: /backend
    command: sh -c "alembic upgrade head && uvicorn run:make_app --factory --host 0.0.0.0 --port 8000 --reload"
    environment:
      - PYTHONPATH=src
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_PUBLIC_ENDPOINT=${S3_PUBLIC_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/ping" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - flower_shop_net


  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running", "-q"]
      interval: 10s
      timeout: 5s
      retries: 8
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    networks:
      - flower_shop_net

  taskiq-worker:
    <<: *backend
    ports: []
    command: [ taskiq, worker, -fsd, -tp, "**tasks/*.py" ,src.core.broker:broker, -w, "1", --max-fails, "1"]

  postgres:
    env_file: .env
    image: postgres:18-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - flower_shop_net
    restart: always

  minio:
    env_file: .env
    build:
      context: ./backend
      dockerfile: minio/Dockerfile
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - flower_shop_net

  redis:
    image: redis:8-alpine
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - flower_shop_net

  redis_gui:
    image: redis/redisinsight
    ports:
      - "5540:5540"
    networks:
      - flower_shop_net

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    command: npm run dev
    networks:
      - flower_shop_net

networks:
  flower_shop_net:
    driver: bridge

volumes:
  postgres-data:
  minio-data:
  redis-data: