services:
  backend:
    &backend
    env_file: .env
    build: ./backend
    restart: always
    volumes:
      - ./backend:/backend
      - ./backend/scripts/entrypoint-backend.sh:/entrypoint-backend.sh
      - ./backend/certs:/backend/certs:ro
    working_dir: /backend
    environment:
      - PYTHONPATH=src
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_PUBLIC_ENDPOINT=${S3_PUBLIC_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
    command: sh -c "alembic upgrade head && uvicorn run:make_app --factory --host ${APP_HOST} --port ${APP_PORT}"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - flower_shop_net

  rabbitmq:
    image: rabbitmq:4-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running", "-q"]
      interval: 10s
      timeout: 5s
      retries: 8
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    networks:
      - flower_shop_net

  worker:
    <<: *backend
    ports: []
    command: taskiq worker core.broker:broker --workers 1 --fs-discover --tasks-pattern **/tasks/*.py
    # command: sh -c "celery -A celery_app:celery_app worker -l info"
    # environment:
    #   - TASKIQ_ADMIN_URL=http://taskiq_admin:3000
    #   - TASKIQ_ADMIN_API_TOKEN=supersecret
    # depends_on:
    #   rabbitmq:
    #     condition: service_healthy
    #   redis:
    #     condition: service_healthy
    #   postgres:
    #     condition: service_healthy


  # taskiq_admin:
  #   image: ghcr.io/taskiq-python/taskiq-admin:latest
  #   container_name: taskiq_admin
  #   ports:
  #     - 3003:3003
  #   environment:
  #     - TASKIQ_ADMIN_API_TOKEN=supersecret
  #   volumes:
  #     - admin_data:/usr/database/
  #   networks:
  #     - flower_shop_net

  postgres:
    env_file: .env
    image: postgres:18-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - flower_shop_net
    restart: always

  minio:
    env_file: .env
    build:
      context: ./backend
      dockerfile: minio/Dockerfile
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - flower_shop_net

  redis:
    image: redis:8-alpine
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - flower_shop_net

  redis_gui:
    image: redis/redisinsight
    ports:
      - "5540:5540"
    networks:
      - flower_shop_net

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    command: npm run dev
    networks:
      - flower_shop_net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=7d"
    networks:
      - flower_shop_net

  promtail:
    image: grafana/promtail:latest
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./infra/promtail/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    privileged: true
    networks:
      - flower_shop_net

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./infra/grafana_loki/loki.yaml:/etc/loki/local-config.yaml
    networks:
      - flower_shop_net

  grafana:
    image: grafana/grafana:latest
    ports:
       - 3000:3000
    volumes:
      - ./infra/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana-data:/var/lib/grafana
    networks:
      - flower_shop_net


networks:
  flower_shop_net:
    driver: bridge

volumes:
  postgres-data:
  minio-data:
  redis-data:
  prometheus-data:
  grafana-data:
  # admin_data: